# Generated by Django 3.0.5 on 2020-04-27 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(default='Беларусь', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('confirmed', models.IntegerField(verbose_name='Количество заболевших')),
                ('deaths', models.IntegerField(verbose_name='Количество умерших')),
                ('recovered', models.IntegerField(verbose_name='Количество выздоровевших')),
                ('tests_made', models.IntegerField(blank=True, null=True, verbose_name='Сделано тестов')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, default='author', max_length=250, null=True)),
                ('source_name', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('img_1', models.URLField(blank=True, null=True)),
                ('img_2', models.URLField(blank=True, null=True)),
                ('img_author', models.CharField(blank=True, default='author', max_length=50, null=True)),
                ('img_title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Беларусь', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('country', models.CharField(default='Беларусь', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
