# Generated by Django 3.0.5 on 2020-04-27 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, default='author', max_length=100)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Беларусь', max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('img_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img_1', to='api.Image')),
                ('img_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img_2', to='api.Image')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location')),
                ('main_img', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_img', to='api.Image')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, default='author', max_length=250)),
                ('source_name', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
                ('img_main_url', models.URLField(blank=True, null=True)),
                ('img_1', models.URLField(blank=True, null=True)),
                ('img_2', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('img_main', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Image')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField(verbose_name='Количество заболевших')),
                ('deaths', models.IntegerField(verbose_name='Количество умерших')),
                ('recovered', models.IntegerField(verbose_name='Количество выздоровевших')),
                ('tests_made', models.IntegerField(blank=True, verbose_name='Сделано тестов')),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
    ]
