# Generated by Django 3.0.5 on 2020-04-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='oblast',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place',
        ),
        migrations.RemoveField(
            model_name='location',
            name='rayon',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Беларусь', max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='dead',
            field=models.IntegerField(verbose_name='Количество умерших'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='disease_name',
            field=models.CharField(max_length=250, verbose_name='Название болезни'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='recovered',
            field=models.IntegerField(verbose_name='Количество выздоровевших'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='sick',
            field=models.IntegerField(verbose_name='Количество заболевших'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='tests_made',
            field=models.IntegerField(verbose_name='Сделано тестов'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/logo/')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('photo', models.ImageField(upload_to='img/project/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('where_is_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_logo', models.ImageField(upload_to='img/logo/')),
                ('src_name', models.CharField(max_length=250)),
                ('src_url', models.URLField()),
                ('photo', models.ImageField(upload_to='img/post/')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('where_is_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('photo', models.ImageField(upload_to='img/photo/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('where_is_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
