# Generated by Django 3.0.5 on 2020-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200422_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='sick',
            new_name='confirmed',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='dead',
            new_name='deaths',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='author',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='disease_name',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='where_is_it',
        ),
        migrations.AddField(
            model_name='fact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='country',
            field=models.CharField(default='Беларусь', max_length=100),
        ),
        migrations.AddField(
            model_name='fact',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
