# Generated by Django 3.0.5 on 2020-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200419_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='src_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo/'),
        ),
    ]
