# Generated by Django 3.0.5 on 2020-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='tests_made',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сделано тестов'),
        ),
    ]
