# Generated by Django 3.0.5 on 2020-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинальный имидж'),
        ),
    ]
