# Generated by Django 3.0.5 on 2020-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200428_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Poster'),
        ),
    ]
